baseurl = "https://argyouth.com/"
title = "The Argumentative Youth"
theme = "arabica-master"
languageCode = "en-us"
copyright = ""
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = ""
    profile = ""
    email = ""
    nick = ""

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "The Argumentative Youth"
    description = ""
    github = "https://github.com/argyouth"
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = ""
    stackoverflow = ""
    microblog = ""
    feedurl = ""
    webmentionEndpoint = ""
    pingbackEndpoint = ""
    micropubEndpoint = ""
    email = ""
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3


